---
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: delegated

platforms:
  - name: ansible01

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer
    ssh_connection:
      pipelining: false

lint: |
  set -e
  yamllint .
  ansible-lint

verifier:
  name: ansible
