# This is an example playbook to prepare Ansible tests.
---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include mdatp"
      ansible.builtin.include_role:
        name: "mdatp"
        tasks_from: prepare
